### ISSUE TITLE
GPS navigation seems to be broken

### ISSUE THREAD

**Issue by salaros** [ockysaurus/kernel_papaya#1]
First of all thank you for the great work you are doing for our device.
After flashing this kernel I started experiencing some wierd lags in all navigation/maps/map-assisted apps (e.g. Uber, carsharing, Yandex maps)
At first the navigation works, but then the map just stop updating.

**Comment by ockaj** [comment]
Hi I will try to fix it
In the meantime please try papaya 1.4 prerelease
https://uploadfiles.io/tf2p9irm
And check if it's fixed or not

**Comment by ockaj** [comment]
Hi i think it was caused by low gpu frequency set by me so i raised it

**Comment by ockaj** [comment]
I released papaya v1.4. Please try it and report if its fixed or not.

**Comment by salaros** [comment]
Will try it and will let you know if it has been fixed + close this bug report

**Comment by salaros** [comment]
1.4 version works much better now
